"""Deterministic Layer A / git / banner hygiene."""

from __future__ import annotations

import re
from dataclasses import dataclass, field

ZWSP_RE = re.compile("[\u200b\u2060\ufeff]")
# Mid-file BOM already in ZWSP_RE via U+FEFF
TAG_RE = re.compile("[\U000e0001\U000e0020-\U000e007e]")  # lone tags, not full flag seqs
BIDI_OVERRIDE_RE = re.compile("[\u202a-\u202e]")

AGENT_TRAILER_RE = re.compile(
    r"(?im)^[ \t]*(?:Co-Authored-By|Co-authored-by):\s*.*(?:"
    r"noreply@anthropic\.com|"
    r"claude(?:\s|$)|"
    r"cursoragent@cursor\.com|"
    r"@cursor\.com|"
    r"copilot@github\.com|"
    r"Copilot\[bot\]|"
    r"codex@openai\.com|"
    r"noreply@openai\.com|"
    r"@users\.noreply\.github\.com"
    r").*$"
)

BANNER_RE = re.compile(
    r"(?im)^[ \t]*(?:#|//|--|/\*|\*|<!--)?[ \t]*"
    r"(?:🤖\s*)?Generated with (?:\[)?Claude Code|"
    r"Generated by Claude|"
    r"Claude-Session:\s*https?://"
    r".*$"
)

HUMAN_EMAIL_OK = re.compile(
    r"(?i)@(?:example\.com|gmail\.com|outlook\.com|proton\.me)\b"
)


@dataclass
class CleanReport:
    suspicious: bool = False
    removed: dict[str, int] = field(default_factory=dict)
    findings: list[str] = field(default_factory=list)

    def add(self, kind: str, n: int, note: str) -> None:
        if n <= 0:
            return
        self.removed[kind] = self.removed.get(kind, 0) + n
        self.findings.append(note)
        self.suspicious = True


def _keep_emoji_zwj(text: str, cleaned: str) -> str:
    """Restore ZWJ only when it sat between emoji bases."""
    if "\u200d" not in text:
        return cleaned
    # If we stripped ZWJ that belonged to an emoji sequence, put those back
    # by never deleting ZWJ next to an emoji codepoint in the first place.
    return cleaned


def _strip_invisible(text: str) -> tuple[str, int]:
    count = 0
    out = []
    i = 0
    n = len(text)
    while i < n:
        ch = text[i]
        if ch == "\u200d":
            prev = out[-1] if out else ""
            nxt = text[i + 1] if i + 1 < n else ""
            if _is_emoji_ish(prev) or _is_emoji_ish(nxt):
                out.append(ch)
                i += 1
                continue
        if ch == "\ufeff" and i == 0:
            out.append(ch)
            i += 1
            continue
        if ZWSP_RE.match(ch) or BIDI_OVERRIDE_RE.match(ch) or TAG_RE.match(ch):
            count += 1
            i += 1
            continue
        out.append(ch)
        i += 1
    return "".join(out), count


def _is_emoji_ish(ch: str) -> bool:
    if not ch:
        return False
    o = ord(ch)
    return (
        0x1F300 <= o <= 0x1FAFF
        or 0x2600 <= o <= 0x27BF
        or 0xFE00 <= o <= 0xFE0F
        or o == 0x200D
    )


def _strip_trailers(text: str) -> tuple[str, int]:
    lines = text.splitlines(keepends=True)
    kept = []
    n = 0
    for line in lines:
        if AGENT_TRAILER_RE.search(line):
            n += 1
            continue
        kept.append(line)
    return "".join(kept), n


def _strip_banners(text: str) -> tuple[str, int]:
    lines = text.splitlines(keepends=True)
    kept = []
    n = 0
    for line in lines:
        if BANNER_RE.search(line):
            n += 1
            continue
        kept.append(line)
    return "".join(kept), n


def clean_text(text: str, name: str = "stdin") -> tuple[str, CleanReport]:
    report = CleanReport()
    out, n = _strip_invisible(text)
    report.add("unicode", n, f"{name}: stripped {n} invisible codepoint(s)")
    out, n = _strip_trailers(out)
    report.add("git-trailer", n, f"{name}: stripped {n} agent trailer(s)")
    out, n = _strip_banners(out)
    report.add("attribution-comment", n, f"{name}: stripped {n} banner line(s)")
    out = _keep_emoji_zwj(text, out)
    return out, report


def inspect_text(text: str, name: str = "stdin") -> CleanReport:
    _, report = clean_text(text, name=name)
    return report
