/** Pure Layer A: invisible Unicode, agent trailers, Generated-with banners. */

export interface LayerARemoved {
  readonly unicode: number
  readonly trailer: number
  readonly banner: number
}

export interface LayerAResult {
  readonly text: string
  readonly removed: LayerARemoved
}

const ZWSP_RE = /[\u200B\u2060\uFEFF]/u
const BIDI_OVERRIDE_RE = /[\u202A-\u202E]/u
const TAG_RE = /[\u{E0001}\u{E0020}-\u{E007E}]/u

const AGENT_TRAILER_RE = new RegExp(
  "^[ \\t]*(?:Co-Authored-By|Co-authored-by):\\s*.*(?:" +
    "noreply@anthropic\\.com|" +
    "claude(?:\\s|$)|" +
    "cursoragent@cursor\\.com|" +
    "@cursor\\.com|" +
    "copilot@github\\.com|" +
    "Copilot\\[bot\\]|" +
    "codex@openai\\.com|" +
    "noreply@openai\\.com|" +
    "@users\\.noreply\\.github\\.com" +
    ").*$",
  "im"
)

const BANNER_RE = new RegExp(
  "^[ \\t]*(?:#|//|--|/\\*|\\*|<!--)?[ \\t]*" +
    "(?:🤖\\s*)?Generated with (?:\\[)?Claude Code|" +
    "Generated by Claude|" +
    "Claude-Session:\\s*https?://" +
    ".*$",
  "im"
)

const isEmojiIsh = (ch: string): boolean => {
  if (ch.length === 0) {
    return false
  }
  const o = ch.codePointAt(0)
  if (o === undefined) {
    return false
  }
  return (
    (o >= 0x1f300 && o <= 0x1faff) ||
    (o >= 0x2600 && o <= 0x27bf) ||
    (o >= 0xfe00 && o <= 0xfe0f) ||
    o === 0x200d
  )
}

const splitKeepEnds = (text: string): Array<string> => {
  const lines = text.match(/[^\r\n]*(?:\r\n|\n|\r)?/g) ?? []
  if (lines.at(-1) === "") {
    lines.pop()
  }
  return lines
}

const stripInvisible = (text: string): { readonly text: string; readonly n: number } => {
  let count = 0
  const out: Array<string> = []
  const chars = [...text]
  for (let i = 0; i < chars.length; i++) {
    const ch = chars[i] ?? ""
    if (ch === "\u200d") {
      const prev = out.at(-1) ?? ""
      const nxt = chars[i + 1] ?? ""
      if (isEmojiIsh(prev) || isEmojiIsh(nxt)) {
        out.push(ch)
        continue
      }
    }
    if (ch === "\ufeff" && i === 0) {
      out.push(ch)
      continue
    }
    if (ZWSP_RE.test(ch) || BIDI_OVERRIDE_RE.test(ch) || TAG_RE.test(ch)) {
      count += 1
      continue
    }
    out.push(ch)
  }
  return { text: out.join(""), n: count }
}

const stripMatchingLines = (
  text: string,
  re: RegExp
): { readonly text: string; readonly n: number } => {
  const kept: Array<string> = []
  let n = 0
  for (const line of splitKeepEnds(text)) {
    if (re.test(line)) {
      n += 1
      continue
    }
    kept.push(line)
  }
  return { text: kept.join(""), n }
}

/** Strip deterministic Layer A marks. Keep emoji ZWJ and a leading BOM. */
export const applyLayerA = (text: string): LayerAResult => {
  const unicode = stripInvisible(text)
  const trailer = stripMatchingLines(unicode.text, AGENT_TRAILER_RE)
  const banner = stripMatchingLines(trailer.text, BANNER_RE)
  return {
    text: banner.text,
    removed: {
      unicode: unicode.n,
      trailer: trailer.n,
      banner: banner.n
    }
  }
}
